/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposIndexRouteImport } from './routes/repos.index'
import { Route as NamespacesIndexRouteImport } from './routes/namespaces.index'
import { Route as ReposSplatRouteImport } from './routes/repos.$'
import { Route as NamespacesSplatRouteImport } from './routes/namespaces.$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIndexRoute = ReposIndexRouteImport.update({
  id: '/repos/',
  path: '/repos/',
  getParentRoute: () => rootRouteImport,
} as any)
const NamespacesIndexRoute = NamespacesIndexRouteImport.update({
  id: '/namespaces/',
  path: '/namespaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposSplatRoute = ReposSplatRouteImport.update({
  id: '/repos/$',
  path: '/repos/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NamespacesSplatRoute = NamespacesSplatRouteImport.update({
  id: '/namespaces/$',
  path: '/namespaces/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/namespaces/$': typeof NamespacesSplatRoute
  '/repos/$': typeof ReposSplatRoute
  '/namespaces/': typeof NamespacesIndexRoute
  '/repos/': typeof ReposIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/namespaces/$': typeof NamespacesSplatRoute
  '/repos/$': typeof ReposSplatRoute
  '/namespaces': typeof NamespacesIndexRoute
  '/repos': typeof ReposIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/namespaces/$': typeof NamespacesSplatRoute
  '/repos/$': typeof ReposSplatRoute
  '/namespaces/': typeof NamespacesIndexRoute
  '/repos/': typeof ReposIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/namespaces/$'
    | '/repos/$'
    | '/namespaces/'
    | '/repos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/namespaces/$'
    | '/repos/$'
    | '/namespaces'
    | '/repos'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/namespaces/$'
    | '/repos/$'
    | '/namespaces/'
    | '/repos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  NamespacesSplatRoute: typeof NamespacesSplatRoute
  ReposSplatRoute: typeof ReposSplatRoute
  NamespacesIndexRoute: typeof NamespacesIndexRoute
  ReposIndexRoute: typeof ReposIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/': {
      id: '/repos/'
      path: '/repos'
      fullPath: '/repos/'
      preLoaderRoute: typeof ReposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namespaces/': {
      id: '/namespaces/'
      path: '/namespaces'
      fullPath: '/namespaces/'
      preLoaderRoute: typeof NamespacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$': {
      id: '/repos/$'
      path: '/repos/$'
      fullPath: '/repos/$'
      preLoaderRoute: typeof ReposSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namespaces/$': {
      id: '/namespaces/$'
      path: '/namespaces/$'
      fullPath: '/namespaces/$'
      preLoaderRoute: typeof NamespacesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  NamespacesSplatRoute: NamespacesSplatRoute,
  ReposSplatRoute: ReposSplatRoute,
  NamespacesIndexRoute: NamespacesIndexRoute,
  ReposIndexRoute: ReposIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
